# Generated by Django 2.1.1 on 2018-09-15 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180915_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usedDate', models.DateTimeField(default=datetime.datetime(2018, 9, 16, 7, 14, 13, 939960), verbose_name='usedDate')),
                ('item', models.CharField(max_length=20, verbose_name='Item')),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('memo', models.CharField(blank=True, max_length=500, verbose_name='memo')),
                ('plan', models.BooleanField(verbose_name='plan')),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'data',
                'ordering': ['usedDate'],
                'get_latest_by': 'usedDate',
            },
        ),
        migrations.RemoveField(
            model_name='modules',
            name='account',
        ),
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='modules',
        ),
    ]
