# Generated by Django 2.1.1 on 2018-09-30 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180916_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='usedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 23, 8, 37, 607293), verbose_name='usedDate'),
        ),
    ]
