# Generated by Django 2.1.1 on 2018-10-03 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180930_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='usedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 18, 18, 49, 604679), verbose_name='usedDate'),
        ),
    ]
