# Generated by Django 2.1.1 on 2018-10-05 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181003_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='usedDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 19, 0, 0, 675363), verbose_name='usedDate'),
        ),
    ]
