# Generated by Django 2.1.1 on 2018-10-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181005_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
